# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(737, 439)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_newuser = QtWidgets.QPushButton(self.centralwidget)
        self.btn_newuser.setGeometry(QtCore.QRect(10, 110, 121, 31))
        self.btn_newuser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_newuser.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";\n"
"border-color: rgb(45, 45, 185);\n"
"background-color: rgb(191, 191, 191);")
        self.btn_newuser.setObjectName("btn_newuser")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(10, 170, 121, 31))
        self.btn_login.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";\n"
"border-color: rgb(45, 45, 185);\n"
"background-color: rgb(191, 191, 191);")
        self.btn_login.setObjectName("btn_login")
        self.l_id = QtWidgets.QLabel(self.centralwidget)
        self.l_id.setGeometry(QtCore.QRect(170, 90, 71, 16))
        self.l_id.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.l_id.setObjectName("l_id")
        self.l_pw = QtWidgets.QLabel(self.centralwidget)
        self.l_pw.setGeometry(QtCore.QRect(170, 130, 56, 12))
        self.l_pw.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.l_pw.setObjectName("l_pw")
        self.l_city = QtWidgets.QLabel(self.centralwidget)
        self.l_city.setGeometry(QtCore.QRect(170, 170, 56, 12))
        self.l_city.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.l_city.setObjectName("l_city")
        self.l_code = QtWidgets.QLabel(self.centralwidget)
        self.l_code.setGeometry(QtCore.QRect(170, 210, 56, 12))
        self.l_code.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.l_code.setObjectName("l_code")
        self.l_mail = QtWidgets.QLabel(self.centralwidget)
        self.l_mail.setGeometry(QtCore.QRect(170, 250, 56, 12))
        self.l_mail.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.l_mail.setObjectName("l_mail")
        self.l_mobile = QtWidgets.QLabel(self.centralwidget)
        self.l_mobile.setGeometry(QtCore.QRect(170, 290, 61, 16))
        self.l_mobile.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.l_mobile.setObjectName("l_mobile")
        self.t_loginid = QtWidgets.QLineEdit(self.centralwidget)
        self.t_loginid.setGeometry(QtCore.QRect(240, 90, 113, 20))
        self.t_loginid.setObjectName("t_loginid")
        self.t_password = QtWidgets.QLineEdit(self.centralwidget)
        self.t_password.setGeometry(QtCore.QRect(240, 130, 113, 20))
        self.t_password.setObjectName("t_password")
        self.t_city = QtWidgets.QLineEdit(self.centralwidget)
        self.t_city.setGeometry(QtCore.QRect(240, 170, 113, 20))
        self.t_city.setObjectName("t_city")
        self.t_pocode = QtWidgets.QLineEdit(self.centralwidget)
        self.t_pocode.setGeometry(QtCore.QRect(240, 210, 113, 20))
        self.t_pocode.setObjectName("t_pocode")
        self.t_email = QtWidgets.QLineEdit(self.centralwidget)
        self.t_email.setGeometry(QtCore.QRect(240, 250, 113, 20))
        self.t_email.setObjectName("t_email")
        self.t_mobileno = QtWidgets.QLineEdit(self.centralwidget)
        self.t_mobileno.setGeometry(QtCore.QRect(240, 290, 113, 20))
        self.t_mobileno.setObjectName("t_mobileno")
        self.Employee_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Employee_check.setGeometry(QtCore.QRect(390, 90, 81, 16))
        self.Employee_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.Employee_check.setObjectName("Employee_check")
        self.TeamLeader_check = QtWidgets.QCheckBox(self.centralwidget)
        self.TeamLeader_check.setGeometry(QtCore.QRect(390, 120, 101, 16))
        self.TeamLeader_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.TeamLeader_check.setObjectName("TeamLeader_check")
        self.Projectmanager_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Projectmanager_check.setGeometry(QtCore.QRect(390, 150, 121, 16))
        self.Projectmanager_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.Projectmanager_check.setObjectName("Projectmanager_check")
        self.AsstProjectManager_check = QtWidgets.QCheckBox(self.centralwidget)
        self.AsstProjectManager_check.setGeometry(QtCore.QRect(390, 180, 141, 16))
        self.AsstProjectManager_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.AsstProjectManager_check.setObjectName("AsstProjectManager_check")
        self.Manager_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Manager_check.setGeometry(QtCore.QRect(390, 210, 81, 16))
        self.Manager_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.Manager_check.setObjectName("Manager_check")
        self.Admin_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Admin_check.setGeometry(QtCore.QRect(390, 240, 81, 16))
        self.Admin_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.Admin_check.setObjectName("Admin_check")
        self.NonEmployee_check = QtWidgets.QCheckBox(self.centralwidget)
        self.NonEmployee_check.setGeometry(QtCore.QRect(550, 90, 121, 16))
        self.NonEmployee_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.NonEmployee_check.setObjectName("NonEmployee_check")
        self.Unregistered_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Unregistered_check.setGeometry(QtCore.QRect(550, 120, 101, 16))
        self.Unregistered_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.Unregistered_check.setObjectName("Unregistered_check")
        self.Registered_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Registered_check.setGeometry(QtCore.QRect(550, 150, 81, 16))
        self.Registered_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.Registered_check.setObjectName("Registered_check")
        self.Student_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Student_check.setGeometry(QtCore.QRect(550, 180, 81, 16))
        self.Student_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.Student_check.setObjectName("Student_check")
        self.Trainee_check = QtWidgets.QCheckBox(self.centralwidget)
        self.Trainee_check.setGeometry(QtCore.QRect(550, 210, 81, 16))
        self.Trainee_check.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.Trainee_check.setObjectName("Trainee_check")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(550, 240, 81, 16))
        self.checkBox_12.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";")
        self.checkBox_12.setObjectName("checkBox_12")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(440, 330, 131, 31))
        self.btn_register.setStyleSheet("font: 75 9pt \"나눔명조 ExtraBold\";\n"
"border-color: rgb(45, 45, 185);\n"
"background-color: rgb(191, 191, 191);")
        self.btn_register.setCheckable(False)
        self.btn_register.setObjectName("btn_register")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_newuser.setText(_translate("MainWindow", "New User"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.l_id.setText(_translate("MainWindow", "Login ID"))
        self.l_pw.setText(_translate("MainWindow", "Password"))
        self.l_city.setText(_translate("MainWindow", "City"))
        self.l_code.setText(_translate("MainWindow", "POCode"))
        self.l_mail.setText(_translate("MainWindow", "Email"))
        self.l_mobile.setText(_translate("MainWindow", "Mobile No"))
        self.Employee_check.setText(_translate("MainWindow", "Employee"))
        self.TeamLeader_check.setText(_translate("MainWindow", "Team Leader"))
        self.Projectmanager_check.setText(_translate("MainWindow", "Project Manager"))
        self.AsstProjectManager_check.setText(_translate("MainWindow", "AsstProject Manager"))
        self.Manager_check.setText(_translate("MainWindow", "Manager"))
        self.Admin_check.setText(_translate("MainWindow", "Admin"))
        self.NonEmployee_check.setText(_translate("MainWindow", "Non-Employee"))
        self.Unregistered_check.setText(_translate("MainWindow", "Unregistered"))
        self.Registered_check.setText(_translate("MainWindow", "Registered"))
        self.Student_check.setText(_translate("MainWindow", "Student"))
        self.Trainee_check.setText(_translate("MainWindow", "Trainee"))
        self.checkBox_12.setText(_translate("MainWindow", "HR"))
        self.btn_register.setText(_translate("MainWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
